import type { VisualTheme } from './types';

// Paleta de cores do Chakra UI
export const chakraColors = {
  gray: {
    50: '#fafafa',
    100: '#f4f4f5',
    200: '#e4e4e7',
    300: '#d4d4d8',
    400: '#a1a1aa',
    500: '#71717a',
    600: '#52525b',
    700: '#3f3f46',
    800: '#27272a',
    900: '#18181b',
    950: '#111111',
  },
  red: {
    50: '#fef2f2',
    100: '#fee2e2',
    200: '#fecaca',
    300: '#fca5a5',
    400: '#f87171',
    500: '#ef4444',
    600: '#dc2626',
    700: '#991919',
    800: '#511111',
    900: '#300c0c',
    950: '#1f0808',
  },
  orange: {
    50: '#fff7ed',
    100: '#ffedd5',
    200: '#fed7aa',
    300: '#fdba74',
    400: '#fb923c',
    500: '#f97316',
    600: '#ea580c',
    700: '#92310a',
    800: '#6c2710',
    900: '#3b1106',
    950: '#220a04',
  },
  yellow: {
    50: '#fefce8',
    100: '#fef9c3',
    200: '#fef08a',
    300: '#fde047',
    400: '#facc15',
    500: '#eab308',
    600: '#ca8a04',
    700: '#845209',
    800: '#713f12',
    900: '#422006',
    950: '#281304',
  },
  green: {
    50: '#f0fdf4',
    100: '#dcfce7',
    200: '#bbf7d0',
    300: '#86efac',
    400: '#4ade80',
    500: '#22c55e',
    600: '#16a34a',
    700: '#116932',
    800: '#124a28',
    900: '#042713',
    950: '#03190c',
  },
  teal: {
    50: '#f0fdfa',
    100: '#ccfbf1',
    200: '#99f6e4',
    300: '#5eead4',
    400: '#2dd4bf',
    500: '#14b8a6',
    600: '#0d9488',
    700: '#0c5d56',
    800: '#114240',
    900: '#032726',
    950: '#021716',
  },
  blue: {
    50: '#eff6ff',
    100: '#dbeafe',
    200: '#bfdbfe',
    300: '#a3cfff',
    400: '#60a5fa',
    500: '#3b82f6',
    600: '#2563eb',
    700: '#173da6',
    800: '#1a3478',
    900: '#14204a',
    950: '#0c142e',
  },
  cyan: {
    50: '#ecfeff',
    100: '#cffafe',
    200: '#a5f3fc',
    300: '#67e8f9',
    400: '#22d3ee',
    500: '#06b6d4',
    600: '#0891b2',
    700: '#0c5c72',
    800: '#134152',
    900: '#072a38',
    950: '#051b24',
  },
  purple: {
    50: '#faf5ff',
    100: '#f3e8ff',
    200: '#e9d5ff',
    300: '#d8b4fe',
    400: '#c084fc',
    500: '#a855f7',
    600: '#9333ea',
    700: '#641ba3',
    800: '#4a1772',
    900: '#2f0553',
    950: '#1a032e',
  },
  pink: {
    50: '#fdf2f8',
    100: '#fce7f3',
    200: '#fbcfe8',
    300: '#f9a8d4',
    400: '#f472b6',
    500: '#ec4899',
    600: '#db2777',
    700: '#a41752',
    800: '#6d0e34',
    900: '#45061f',
    950: '#2c0514',
  },
};

// Tema padrão (financeiro profissional)
export const defaultTheme: VisualTheme = {
  id: 'default',
  name: 'Default',
  colors: {
    // Cores principais do tema
    primary: 'blue',
    secondary: 'green',
    accent: 'yellow',
    gray: 'gray',
    revenue: 'green',
    expense: 'red',
    chakraColors: {
      red: 'red',
      green: 'green',
      yellow: 'yellow',
      purple: 'purple',
      blue: 'blue',
      cyan: 'cyan',
      pink: 'pink',
      orange: 'orange',
      teal: 'teal',
      gray: 'gray',
      white: 'white',
      black: 'black',
    },
    // Tokens semânticos
    background: {
      primary: 'blue.800',
      secondary: 'blue.700',
      tertiary: 'blue.600',
      quaternary: 'blue.50',
      selected: 'blue.500',
      noSelect: 'gray.200',
      hover: 'gray.700',
      header: 'blue.800',
      navigation: 'blue.800',
      lastRegistrations: {
        expense: 'red.50',
        revenue: 'green.50',
        neutral: 'gray.200',
        badge: {
          expense: 'red.100',
          revenue: 'green.100',
        },
      },
      loading: 'blue.500',
      summaryCard: {
        revenue: 'green.200',
        expense: 'red.200',
      },
      login: 'rgba(23, 25, 35, 0.8)',
      reports: 'blue.50',
      coin: 'blue.700',
      home: 'blue.50',
      dashboard: 'blue.50',
      resources: 'blue.50',
      profile: {
        primary: 'blue.50',
        secondary: 'blue.600',
        selected: 'white',
      },
      dateRangeFilter: 'blue.200',
      qrScanner: 'blue.500',
    },
    text: {
      primary: 'white',
      secondary: 'gray.300',
      tertiary: 'gray.200',
      accent: 'blue.300',
      disabled: 'gray.500',
      link: 'blue.300',

      coin: 'yellow.500',
      summaryCard: {
        revenue: 'green.700',
        expense: 'red.700',
      },
      lastRegistrations: {
        title: 'blue.800',
        primary: 'black',
        icon: 'blue.800',
        neutral: 'gray.500',
        expense: 'red.500',
        revenue: 'green.500',
      },
      reports: {
        title: 'blue.800',
        primary: 'blue.600',
        icon: 'blue.800',
        neutral: 'gray.500',
        expense: 'red.500',
        revenue: 'green.500',
      },
      header: 'white',
      navigation: {
        active: 'blue.800',
        inactive: 'white',
      },
      hover: {
        expense: 'blue.700',
        revenue: 'blue.700',
        neutral: 'blue.700',
        inverse: 'blue.800',
      },
      eye: 'blue.500',
      dateRangeFilter: 'blue.800',
      profile: {
        primary: 'blue.800',
        secondary: 'blue.500',
        selected: 'white',
      },
    },
    heading: {
      summaryCard: {
        revenue: 'green.700',
        expense: 'red.700',
      },
    },
    border: {
      primary: 'blue.700',
      secondary: 'gray.600',
      selected: 'blue.500',
      noSelect: 'gray.200',
      lastRegistrations: {
        expense: 'red.500',
        revenue: 'green.500',
        neutral: 'gray.700',
      },
      summaryCard: {
        revenue: 'green.500',
        expense: 'red.500',
      },
      reports: 'black',
      header: 'blue.900',
      navigation: 'blue.900',
      coin: 'blue.700',
    },
    status: {
      success: 'green.300',
      error: 'red.300',
      warning: 'yellow.300',
      info: 'blue.300',
    },
    button: {
      primary: 'blue',
      secondary: 'blue',
      danger: 'red',
      warning: 'yellow',
      background: {
        primary: 'blue.800',
        expense: 'blue.500',
        revenue: 'green.500',
        neutral: 'blue.500',
        inverse: 'white',
      },
      text: {
        primary: 'white',
        expense: 'white',
        revenue: 'white',
      },
      border: {
        expense: 'blue.800',
        revenue: 'blue.800',
        neutral: 'blue.800',
      },
      hover: {
        text: {
          default: 'white',
          expense: 'white',
          revenue: 'white',
          neutral: 'white',
          inverse: 'blue.800',
        },
        background: {
          default: 'white',
          expense: 'white',
          revenue: 'white',
          neutral: 'blue.800',
          inverse: 'white',
        },
        border: {
          default: 'blue.800',
          expense: 'blue.800',
          revenue: 'green.800',
          neutral: 'blue.800',
          inverse: 'blue.800',
        },
      },
    },
    link: {
      primary: 'blue.300',
    },
    input: {
      primary: 'white',
      secondary: 'gray.200',
      hover: 'transparent',
      focus: 'transparent',
      border: 'white',
      background: 'transparent',
      focusBorder: 'blue.600',
      backgroundPrimary: 'blue.600',
      backgroundSecondary: 'blue.700',
      focusPrimary: 'transparent',
    },
  },
  fonts: {
    body: "'Roboto', sans-serif",
    heading: "'Poppins', sans-serif",
    mono: "'Roboto Mono', monospace",
    theme: "'Roboto', sans-serif",
  },
  assets: {
    images: {
      logo: '/assets/images/logo-default.png',
      background: {
        login: '/assets/images/login-bg-default.png',
        register: '/assets/images/register-bg-default.png',
        notFound: '/assets/images/notfound-bg-default.png',
        underConstruction: '/assets/images/under-construction-bg-default.png',
      },
      coatOfArms: {
        family: '/assets/images/coat_of_arms_family.png',
        solare: '/assets/images/coat_of_arms_solare.png',
      },
      goldCoin: '/assets/images/3d-coin.gif',
    },
    animations: {
      loading: {
        save: '/assets/images/wallet-animation.gif',
        read: '/assets/images/wallet-money-added.gif',
        open: '/assets/images/wallet-money-added.gif',
      },
    },
  },
};

// Tema RPG medieval
export const rpgTheme: VisualTheme = {
  id: 'rpg',
  name: 'RPG Medieval',
  colors: {
    primary: 'purple',
    secondary: 'red',
    accent: 'yellow',
    gray: 'gray',
    revenue: 'green',
    expense: 'red',
    chakraColors: {
      red: 'red',
      green: 'green',
      yellow: 'yellow',
      purple: 'purple',
      blue: 'blue',
      cyan: 'cyan',
      pink: 'pink',
      orange: 'orange',
      teal: 'teal',
      gray: 'gray',
      white: 'white',
      black: 'black',
    },
    // Tokens semânticos
    background: {
      primary: 'purple.800',
      secondary: 'purple.700',
      tertiary: 'purple.600',
      quaternary: 'purple.50',
      selected: 'purple.500',
      noSelect: 'gray.200',
      hover: 'gray.700',
      header: 'purple.800',
      navigation: 'purple.800',
      lastRegistrations: {
        expense: 'red.50',
        revenue: 'green.50',
        neutral: 'gray.200',
        badge: {
          expense: 'red.100',
          revenue: 'green.100',
        },
      },
      loading: 'purple.500',
      summaryCard: {
        revenue: 'green.200',
        expense: 'red.200',
      },
      login: 'rgba(23, 25, 35, 0.8)',
      reports: 'purple.50',
      coin: 'purple.700',
      home: 'purple.50',
      dashboard: 'purple.50',
      resources: 'purple.50',
      profile: {
        primary: 'purple.50',
        secondary: 'purple.600',
        selected: 'white',
      },
      dateRangeFilter: 'purple.200',
      qrScanner: 'purple.500',
    },
    text: {
      primary: 'white',
      secondary: 'gray.500',
      tertiary: 'gray.200',
      accent: 'purple.800',
      disabled: 'gray.500',
      link: 'purple.300',
      coin: 'yellow.500',
      summaryCard: {
        revenue: 'green.700',
        expense: 'red.700',
      },
      lastRegistrations: {
        title: 'purple.800',
        primary: 'black',
        icon: 'purple.800',
        neutral: 'gray.500',
        expense: 'red.500',
        revenue: 'green.500',
      },
      reports: {
        title: 'purple.800',
        primary: 'purple.600',
        icon: 'purple.800',
        neutral: 'gray.500',
        expense: 'red.500',
        revenue: 'green.500',
      },
      header: 'white',
      navigation: {
        active: 'purple.800',
        inactive: 'white',
      },
      hover: {
        expense: 'purple.700',
        revenue: 'purple.700',
        neutral: 'purple.700',
        inverse: 'purple.800',
      },
      eye: 'purple.500',
      dateRangeFilter: 'purple.800',
      profile: {
        primary: 'purple.800',
        secondary: 'purple.500',
        selected: 'white',
      },
    },
    heading: {
      summaryCard: {
        revenue: 'white',
        expense: 'white',
      },
    },
    border: {
      primary: 'purple.700',
      secondary: 'gray.600',
      selected: 'purple.500',
      noSelect: 'gray.200',
      lastRegistrations: {
        expense: 'red.500',
        revenue: 'green.500',
        neutral: 'gray.700',
      },
      summaryCard: {
        revenue: 'green.500',
        expense: 'red.500',
      },
      reports: 'purple.500',
      header: 'purple.900',
      navigation: 'purple.900',
      coin: 'purple.700',
    },
    status: {
      success: 'green.300',
      error: 'red.300',
      warning: 'yellow.300',
      info: 'purple.300',
    },
    button: {
      primary: 'purple',
      secondary: 'purple',
      danger: 'red',
      warning: 'yellow',
      background: {
        primary: 'purple.800',
        expense: 'purple.500',
        revenue: 'green.500',
        neutral: 'purple.500',
        inverse: 'white',
      },
      text: {
        primary: 'white',
        expense: 'white',
        revenue: 'white',
      },
      border: {
        expense: 'purple.500',
        revenue: 'green.500',
        neutral: 'purple.500',
      },
      hover: {
        text: {
          default: 'white',
          expense: 'white',
          revenue: 'white',
          neutral: 'white',
          inverse: 'purple.800',
        },
        background: {
          default: 'white',
          expense: 'white',
          revenue: 'white',
          neutral: 'purple.800',
          inverse: 'white',
        },
        border: {
          default: 'purple.800',
          expense: 'purple.800',
          revenue: 'green.800',
          neutral: 'purple.800',
          inverse: 'purple.800',
        },
      },
    },
    link: {
      primary: 'blue.300',
    },
    input: {
      primary: 'white',
      secondary: 'gray.200',
      hover: 'transparent',
      focus: 'transparent',
      border: 'white',
      background: 'transparent',
      focusBorder: 'blue.600',
      backgroundPrimary: 'purple.600',
      backgroundSecondary: 'purple.700',
      focusPrimary: 'transparent',
    },
  },
  fonts: {
    body: 'system-ui',
    heading: 'Helvetica',
    mono: "'Press Start 2P', cursive",
    theme: "'Pixelify Sans', sans-serif",
  },
  assets: {
    images: {
      logo: '/assets/images/logo-medieval.png',
      background: {
        login: '/assets/images/login-bg-medieval.png',
        register: '/assets/images/register-bg-medieval.png',
        notFound: '/assets/images/notfound-bg-medieval.png',
        underConstruction: '/assets/images/under-construction-bg-medieval.png',
      },
      coatOfArms: {
        family: '/assets/images/coat_of_arms_family.png',
        solare: '/assets/images/coat_of_arms_solare.png',
      },
      goldCoin: '/assets/images/gold-coin.gif',
    },
    animations: {
      loading: {
        save: '/assets/images/knigth-solare.gif',
        read: '/assets/images/knigth-loading.gif',
        open: '/assets/images/bonfire.gif',
      },
    },
  },
};